package com.cheques.pojos;
// Generated Jul 6, 2022 9:15:07 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Conceptopago generated by hbm2java
 */
public class Conceptopago implements java.io.Serializable {

    private Integer idconceptopago;
    private String descripcion;
    private Integer estado;
    private Integer idcreo;
    private Date fechacreacion;
    private boolean habilitado;

    public Conceptopago() {
    }


    public Integer getIdconceptopago() {
        return this.idconceptopago;
    }

    public void setIdconceptopago(Integer idconceptopago) {
        this.idconceptopago = idconceptopago;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Integer getEstado() {
        return estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }

 

    public Integer getIdcreo() {
        return idcreo;
    }

    public void setIdcreo(Integer idcreo) {
        this.idcreo = idcreo;
    }

    public Date getFechacreacion() {
        return fechacreacion;
    }

    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }

    public boolean isHabilitado() {
        return this.habilitado;
    }

    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }
}
