package com.cheques.pojos;
// Generated 03/31/2021 12:13:54 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usuarioacceso generated by hbm2java
 */
public class Usuarioacceso  implements java.io.Serializable {


     private Integer idusuarioacceso;
     private Usuarios usuarios;
     private Integer idciudadano;
     private int idsistema;
     private boolean fallido;
     private String ip;
     private Date fechaacceso;
     private String username;
     private Integer idusuarioexpediente;
     private boolean habilitado;

    public Usuarioacceso() {
    }

	
    public Usuarioacceso(int idsistema, boolean fallido, String ip, Date fechaacceso, boolean habilitado) {
        this.idsistema = idsistema;
        this.fallido = fallido;
        this.ip = ip;
        this.fechaacceso = fechaacceso;
        this.habilitado = habilitado;
    }
    public Usuarioacceso(Usuarios usuarios, Integer idciudadano, int idsistema, boolean fallido, String ip, Date fechaacceso, String username, Integer idusuarioexpediente, boolean habilitado) {
       this.usuarios = usuarios;
       this.idciudadano = idciudadano;
       this.idsistema = idsistema;
       this.fallido = fallido;
       this.ip = ip;
       this.fechaacceso = fechaacceso;
       this.username = username;
       this.idusuarioexpediente = idusuarioexpediente;
       this.habilitado = habilitado;
    }
   
    public Integer getIdusuarioacceso() {
        return this.idusuarioacceso;
    }
    
    public void setIdusuarioacceso(Integer idusuarioacceso) {
        this.idusuarioacceso = idusuarioacceso;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public Integer getIdciudadano() {
        return this.idciudadano;
    }
    
    public void setIdciudadano(Integer idciudadano) {
        this.idciudadano = idciudadano;
    }
    public int getIdsistema() {
        return this.idsistema;
    }
    
    public void setIdsistema(int idsistema) {
        this.idsistema = idsistema;
    }
    public boolean isFallido() {
        return this.fallido;
    }
    
    public void setFallido(boolean fallido) {
        this.fallido = fallido;
    }
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    public Date getFechaacceso() {
        return this.fechaacceso;
    }
    
    public void setFechaacceso(Date fechaacceso) {
        this.fechaacceso = fechaacceso;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Integer getIdusuarioexpediente() {
        return this.idusuarioexpediente;
    }
    
    public void setIdusuarioexpediente(Integer idusuarioexpediente) {
        this.idusuarioexpediente = idusuarioexpediente;
    }
    public boolean isHabilitado() {
        return this.habilitado;
    }
    
    public void setHabilitado(boolean habilitado) {
        this.habilitado = habilitado;
    }




}


